const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const fields=new Map();let n=0;
const ctx=vm.createContext({S:{year:[{t:'旧年度目标',items:[],records:[{text:'历史'}],nextAction:'旧下一步'}],monthPlansByYear:{'2026':{'2026-09':{plan:'旧月目标',actual:'原实际',reason:'原复盘',status:'part'}}}},isDoneEver:t=>!!t.logged,save(){},renderLongterm(){},id:()=>`task-${++n}`,todayStr:()=> '2026-09-28',confirm:()=>true,document:{getElementById:k=>fields.get(k)}});
vm.runInContext(fs.readFileSync('assets/goals.js','utf8'),ctx);
ctx.document.querySelectorAll=()=>[];
const run=s=>vm.runInContext(s,ctx);
fields.set('plan-add-year-0',{value:'拆分步骤'});
for(let i=0;i<6;i++){fields.get('plan-add-year-0').value='拆分步骤';run("addPlanTask('year','0')");}assert.equal(ctx.S.year[0].items.length,5);
run("setPlanTask('year','0',0,'done',true)");assert.equal(run("planProgress(S.year[0],'year')"),20);
assert.equal(run('planTaskOrder(S.year[0].items).at(-1).i'),0);
run("setPlanTask('year','0',3,'priority','high');setPlanTask('year','0',2,'due','2026-10-01')");assert.equal(run('planTaskOrder(S.year[0].items)[0].i'),3);assert.equal(run('planTaskOrder(S.year[0].items)[1].i'),2);
run("setPlanField('year','0','progress',67);setPlanTask('year','0',1,'done',true)");assert.equal(run("planProgress(S.year[0],'year')"),67);
run("setPlanField('year','0','auto',true)");assert.equal(run("planProgress(S.year[0],'year')"),40);
run("setPlanField('year','0','done',true)");assert.equal(run("planProgress(S.year[0],'year')"),100);
run("setPlanField('year','0','done',false);removePlanTask('year','0',4)");assert.equal(ctx.S.year[0].items.length,4);assert.equal(ctx.S.year[0].removedPlanTasks.length,1);
assert.equal(ctx.S.year[0].records[0].text,'历史');assert.equal(ctx.S.year[0].nextAction,'旧下一步');
fields.set('plan-add-month-2026-09',{value:'月任务'});
run("addPlanTask('month','2026-09');setPlanTask('month','2026-09',0,'done',true)");assert.equal(run("planProgress(planGoal('month','2026-09'),'month')"),100);
run("setPlanField('month','2026-09','done',true);setPlanField('month','2026-09','done',false)");
const month=ctx.S.monthPlansByYear['2026']['2026-09'];assert.equal(month.status,'part');assert.equal(month.plan,'旧月目标');assert.equal(month.actual,'原实际');assert.equal(month.reason,'原复盘');
const core=fs.readFileSync('assets/core-state.js','utf8');run(core.match(/S\.year = S\.year\.map\(c=>\(\{[^\n]+/)[0]);assert.equal(ctx.S.year[0].items[0].planDone,true);
console.log('PASS: five-task limit, priority/due ordering, completed tasks last, manual/automatic progress, completion undo, retained monthly/annual history.');
