const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const original=[{id:'legacy',npc:'lin',t:'原有未完成委托',branch:true,choices:[{t:'原选择',xp:20}],done:false},{id:'finished',npc:'yun',t:'原有已完成委托',done:true,xp:30,chat:[{who:'me',t:'保留记录'}]}];
const ctx=vm.createContext({S:{npc:{active:structuredClone(original)}},NPCS:[{id:'lin',a:'BADMINTON'},{id:'shen',a:'CAREER'},{id:'yun',a:'BODY'},{id:'bailu',a:'MIND'}],id:(()=>{let n=0;return()=>`new-${++n}`})(),save(){}});
vm.runInContext(fs.readFileSync('assets/refinement.js','utf8'),ctx);
vm.runInContext('ensurePracticalNpcTasks();ensurePracticalNpcTasks()',ctx);
assert.equal(ctx.S.npc.active.length,14);
assert.equal(JSON.stringify(ctx.S.npc.active.slice(0,2)),JSON.stringify(original));
assert.equal(ctx.S.npc.active.filter(q=>q.practical&&q.npc==='lin').length,3);
assert.equal(new Set(ctx.S.npc.active.map(q=>q.id)).size,14);
ctx.S.npc.active=[structuredClone(original[0])];
vm.runInContext('ensurePracticalNpcTasks()',ctx);
assert.equal(ctx.S.npc.active.length,13);
assert.equal(JSON.stringify(ctx.S.npc.active[0]),JSON.stringify(original[0]));
console.log('PASS: practical NPC actions append once, preserve original tasks/choices/chat/IDs, and support a new weekly list.');
const core=fs.readFileSync('assets/core-state.js','utf8');
const migration=core.slice(core.indexOf('  // One-time addition;'),core.indexOf('  S.pets.forEach(function(p){',core.indexOf('  // One-time addition;')));
const pets=vm.createContext({S:{pets:[{name:'土豆',notes:'原资料'}]}});
vm.runInContext(migration,pets);vm.runInContext(migration,pets);
assert.equal(pets.S.pets.length,2);assert.equal(pets.S.pets[0].notes,'原资料');
assert.equal(pets.S.pets[1].birthday,'2022-09-27');assert.equal(pets.S.pets[1].adopted,'2026-09-27');assert.equal(pets.S.pets[1].ageEstimated,true);
const custom=vm.createContext({S:{pets:[{name:'牡丹',notes:'用户已有资料',birthday:'2022-09-27'}]}});
vm.runInContext(migration,custom);assert.equal(custom.S.pets.length,1);assert.equal(custom.S.pets[0].notes,'用户已有资料');
console.log('PASS: Mudan added once; existing pets and user-edited Mudan profile preserved.');
